<div class="hide"><h3>Oops, you've reached this page in error.<br />Please visit <a href="http://andrewqtran.com">andrewqtran.com</a> for a complete experience.</h3><hr /></div>
             <h2>Hello!</h2><p>I'm Andrew, a <a href="http://bmc.med.utoronto.ca/bmc/" target="_blank" title="Visit the Master of Biomedical Communications program">biomedical communicator</a>, <a href="https://medium.com/@ericeriksson/what-is-product-design-9709572cb3ff" target="_blank" title="What is product design? Read on Medium">product designer</a>, and front-end web developer. I help people and companies in the healthcare and biomedical industries translate complex problems into elegant visual solutions. Currently, I'm a scientific graphic designer for <a href="http://www.loni.usc.edu/" target="_blank" title="Laboratory of Neuro Imaging">LONI</a> and a designer/developer for <a href="http://alz.care" target="_blank">AlzCare Labs</a>. 
            <p>I'm in the process of rebuilding this site, so please visit my <a href="//www.behance.net/andrewqtran" title="Behance portfolio">Behance portfolio</a> for a more complete project collection.</p>
                        <div class="clear"></div>
            <h2>Some rambling about my background<span class="more" id="bio1" title="Expand to read more"><i class="icon-plus-sign"></i></span></h2>
            <div class="compact" id="bio1">
              <p>Previously, I was a  researcher in drug discovery  research in  academia (<a href="http://pet.ucla.edu/" target="_blank">UCLA</a>) and the biotech industry (<a href="http://www.amgen.com/" target="_blank">Amgen</a> and <a href="http://www.nibr.com/" target="_blank">Novartis</a>). My experience in biotechnology research and development included  drug discovery and pharmacology in immunology and oncology, with  specialties in multiple <em>in vivo</em> imaging modalities.</p> 
              <p>It was exciting to work with cutting edge biomedical technologies, and I soon developed the passion to share those same exciting scientific breakthroughs to a larger audience. In 2010, I discovered the field of medical illustration by chance and immediately went on a two-year mission to <strong>trade pipettes for pencils</strong>. I started working on my previously neglected art skills at night and on weekends until my admission to the <a href="http://bmc.med.utoronto.ca/bmc/" target="_blank">MScBMC program</a> in 2012.</p>
            
              <h2>From bench to bedside <span style="font-size:smaller; color:#999">(&amp; cells to society, too)</span></h2>
              <p>Now in the field of biomedical communications, I still strive for  moving research from bench to bedside.  Instead of working on drugs or therapies with  potential applications for patients and society, I now work on translating the  research to the same audience. Patients need to know and understand the procedures and treatments they receive. Society needs to understand the significance of biomedical research and medical advances.</p>
              <h2>Biomedical communications?</h2>
              <p>Still confused about what exactly biomedical communications  or medical illustration is? Today, the definition for &quot;medical  illustration&quot; has evolved (and still is) beyond the stereotypical  &quot;textbook illustrations&quot;. </p>
              <p>Medical illustrators have taken on 3D molecular animation,  software development, infographic design, game development, digital textbook  publishing, and much more -- all for the sake of creating compelling  visualizations and educational tools to illuminate complex medical and  scientific concepts. With rapidly emerging media technology and more accessible  consumer devices, the possibilities are endless. For this reason, some of us call ourselves &quot;biomedical visualizers&quot; or &quot;biomedical communicators.&quot; Learn more at <a href="http://www.ami.org/" target="_blank">the Association of Medical Illustrators</a>.</p>
              <h2>Are you interested in pursuing this career?</h2>
              <p>Don't be shy; please feel free to <a href="#contact" class="smoothScroll">contact me</a> for more information. I've been through the process, and would love to give you the guidance I received on my way here.</p>
            </div>
        